import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Naxbar from '@/components/Naxbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="max-w-screen">
          <Naxbar />
          <div className="max-w-4x1 mx-auto mt-4">(children)</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
